services:
  backend:
    container_name: nestjs
    image: nestjs
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - local-network
    # depends_on:
    #   - database

  # database:
  #   container_name: mysql
  #   image: mysql:8.3
  #   env_file:
  #     - .env
  #   ports:
  #     - '3306:3306'
  #   networks:
  #     - nestjs-api-network
  #   volumes:
  #     - ./db/conf.d:/etc/mysql/conf.d
  #     - ./db/data:/var/lib/mysql
  #     - ./db/initdb.d:/docker-entrypoint-initdb.d
  #   environment:
  #     TZ: Asia/Seoul
  #   restart: always
networks:
  local-network:
    driver: bridge
